### ISSUE TITLE
hygieia-svn-collector

### ISSUE THREAD

**Issue by shubhamk0305** [Hygieia/hygieia-subversion-scm-collector#22]
[root@hygieia target]# java -jar subversion-collector.jar --spring.config.name=subversion --spring.config.location=/home/hygieia/Hygieia-master/collectors/scm/hygieia-scm-subversion-collector-master/svn.properties
15:58:10,800 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
15:58:10,801 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
15:58:10,801 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/home/hygieia/Hygieia-master/collectors/scm/hygieia-scm-subversion-collector-master/target/subversion-collector.jar!/logback.xml]
15:58:10,802 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
15:58:10,803 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/home/hygieia/Hygieia-master/collectors/scm/hygieia-scm-subversion-collector-master/target/subversion-collector.jar!/lib/core-3.0.4.jar!/logback.xml]
15:58:10,803 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/home/hygieia/Hygieia-master/collectors/scm/hygieia-scm-subversion-collector-master/target/subversion-collector.jar!/logback.xml]
15:58:10,877 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@30f673f - URL [jar:file:/home/hygieia/Hygieia-master/collectors/scm/hygieia-scm-subversion-collector-master/target/subversion-collector.jar!/logback.xml] is not of type file
15:58:11,011 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
15:58:21,023 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
15:58:21,046 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
15:58:21,119 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
15:58:21,256 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
15:58:21,274 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ROLLING]
15:58:21,351 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - No compression will be used
15:58:21,352 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern logs/sourcecode-collector-%d{yyyy-MM-dd}.%i.log for the active file
15:58:21,355 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@cf6d783 - The date pattern is 'yyyy-MM-dd' from file name pattern 'logs/sourcecode-collector-%d{yyyy-MM-dd}.%i.log'.
15:58:21,355 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@cf6d783 - Roll-over at midnight.
15:58:21,358 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@cf6d783 - Setting initial period to Sun Jan 26 15:58:21 IST 2020
15:58:21,360 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
15:58:21,366 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ROLLING] - Active log file name: logs/sourcecode-collector-2020-01-26.0.log
15:58:21,366 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ROLLING] - File property is set to [null]
15:58:21,367 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
15:58:21,367 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ROLLING] to Logger[ROOT]
15:58:21,368 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
15:58:21,368 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
15:58:21,369 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@13d9fe30 - Registering current configuration as safe fallback point

2020-01-26 15:58:42,752 [main] INFO  o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@6d1768ae: startup date [Sun Jan 26 15:58:42 IST 2020]; root of context hierarchy
2020-01-26 15:58:43,133 [main] INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2020-01-26 15:58:43,271 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'configurationPropertiesRebinderAutoConfiguration' of type [class org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$601e2361] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
_    _             _      _              _____                           _____          _              _____      _ _           _
| |  | |           (_)    (_)            / ____|                         / ____|        | |            / ____|    | | |         | |
| |__| |_   _  __ _ _  ___ _  __ _ _____| (___   ___  _   _ _ __ ___ ___| |     ___   __| | ___ ______| |     ___ | | | ___  ___| |_ ___  _ __
|  __  | | | |/ _` | |/ _ \ |/ _` |______\___ \ / _ \| | | | '__/ __/ _ \ |    / _ \ / _` |/ _ \______| |    / _ \| | |/ _ \/ __| __/ _ \| '__|
| |  | | |_| | (_| | |  __/ | (_| |      ____) | (_) | |_| | | | (_|  __/ |___| (_) | (_| |  __/      | |___| (_) | | |  __/ (__| || (_) | |
|_|  |_|\__, |\__, |_|\___|_|\__,_|     |_____/ \___/ \__,_|_|  \___\___|\_____\___/ \__,_|\___|       \_____\___/|_|_|\___|\___|\__\___/|_|
        __/ | __/ |
       |___/ |___/

2020-01-26 15:58:53,947 [main] INFO  o.s.c.c.c.ConfigServicePropertySourceLocator - Fetching config from server at: http://localhost:8888
2020-01-26 15:58:54,303 [main] WARN  o.s.c.c.c.ConfigServicePropertySourceLocator - Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/default": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)
2020-01-26 15:58:54,305 [main] INFO  com.capitalone.dashboard.Application - No profiles are active
2020-01-26 15:58:54,338 [main] INFO  o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@472b826e: startup date [Sun Jan 26 15:58:54 IST 2020]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@6d1768ae
2020-01-26 15:58:56,885 [main] INFO  o.s.cloud.context.scope.GenericScope - BeanFactory id=98d79f89-c061-3827-975f-862af46c43ab
2020-01-26 15:58:56,890 [main] INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Post-processing PropertySource instances
2020-01-26 15:58:56,921 [main] INFO  c.u.j.c.StringEncryptorConfiguration - String Encryptor custom Bean not found with name 'jasyptStringEncryptor'. Initializing String Encryptor based on properties with name 'jasyptStringEncryptor'
2020-01-26 15:58:56,942 [main] INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource commandLineArgs [org.springframework.core.env.SimpleCommandLinePropertySource] to EncryptableEnumerablePropertySourceWrapper
2020-01-26 15:58:56,943 [main] INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource systemProperties [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
2020-01-26 15:58:56,943 [main] INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource systemEnvironment [org.springframework.core.env.SystemEnvironmentPropertySource] to EncryptableMapPropertySourceWrapper
2020-01-26 15:58:56,943 [main] INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource random [org.springframework.boot.context.config.RandomValuePropertySource] to EncryptablePropertySourceWrapper
2020-01-26 15:58:56,943 [main] INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource applicationConfig: [file:/home/hygieia/Hygieia-master/collectors/scm/hygieia-scm-subversion-collector-master/svn.properties] [org.springframework.core.env.PropertiesPropertySource] to EncryptableMapPropertySourceWrapper
2020-01-26 15:58:56,943 [main] INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource springCloudClientHostInfo [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
2020-01-26 15:58:56,943 [main] INFO  c.u.j.EnableEncryptablePropertySourcesPostProcessor - Converting PropertySource defaultProperties [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
2020-01-26 15:58:56,947 [main] INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2020-01-26 15:58:57,043 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [class org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$601e2361] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-01-26 15:58:57,239 [main] INFO  o.s.s.c.ThreadPoolTaskScheduler - Initializing ExecutorService  'taskScheduler'
2020-01-26 15:58:57,411 [main] INFO  c.c.dashboard.config.MongoConfig - ReplicaSet[false if you are not using MongoDB replicaset]
2020-01-26 15:58:57,580 [main] INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: localhost:27017
2020-01-26 15:59:07,639 [main] INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2020-01-26 15:59:07,733 [main] INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, writeConcern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@f84e0907, minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=60000, maxConnectionLifeTime=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@2450fe1, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@14f11e1d, socketFactory=javax.net.DefaultSocketFactory@736a091b, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=60000, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2020-01-26 15:59:08,306 [cluster-ClusterId{value='5e2d69f36300dd2b7bb150dd', description='null'}-localhost:27017] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:1, serverValue:12468}] to localhost:27017
2020-01-26 15:59:08,339 [cluster-ClusterId{value='5e2d69f36300dd2b7bb150dd', description='null'}-localhost:27017] INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 0, 10]}, minWireVersion=0, maxWireVersion=7, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=16200843}
2020-01-26 15:59:08,594 [main] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:2, serverValue:12469}] to localhost:27017
2020-01-26 15:59:09,520 [main] INFO  c.c.dashboard.config.MongoConfig - ReplicaSet[false if you are not using MongoDB replicaset]
2020-01-26 15:59:09,520 [main] INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: localhost:27017
2020-01-26 15:59:09,520 [main] INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2020-01-26 15:59:09,562 [main] INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, writeConcern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@f84e0907, minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=60000, maxConnectionLifeTime=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@2450fe1, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@14f11e1d, socketFactory=javax.net.DefaultSocketFactory@736a091b, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=60000, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2020-01-26 15:59:09,569 [main] INFO  c.c.dashboard.config.MongoConfig - ReplicaSet[false if you are not using MongoDB replicaset]
2020-01-26 15:59:09,570 [main] INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: localhost:27017
2020-01-26 15:59:09,570 [main] INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2020-01-26 15:59:09,593 [main] INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, writeConcern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@f84e0907, minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=60000, maxConnectionLifeTime=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@2450fe1, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@14f11e1d, socketFactory=javax.net.DefaultSocketFactory@736a091b, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=60000, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2020-01-26 15:59:09,771 [cluster-ClusterId{value='5e2d69f56300dd2b7bb150de', description='null'}-localhost:27017] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:3, serverValue:12470}] to localhost:27017
2020-01-26 15:59:09,772 [cluster-ClusterId{value='5e2d69f56300dd2b7bb150de', description='null'}-localhost:27017] INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 0, 10]}, minWireVersion=0, maxWireVersion=7, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=551167}
2020-01-26 15:59:09,861 [cluster-ClusterId{value='5e2d69f56300dd2b7bb150df', description='null'}-localhost:27017] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:4, serverValue:12471}] to localhost:27017
2020-01-26 15:59:09,891 [cluster-ClusterId{value='5e2d69f56300dd2b7bb150df', description='null'}-localhost:27017] INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 0, 10]}, minWireVersion=0, maxWireVersion=7, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=1825149}
2020-01-26 15:59:10,981 [main] INFO  c.c.dashboard.config.MongoConfig - ReplicaSet[false if you are not using MongoDB replicaset]
2020-01-26 15:59:10,982 [main] INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: localhost:27017
2020-01-26 15:59:10,997 [main] INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2020-01-26 15:59:11,034 [main] INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, writeConcern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@f84e0907, minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=60000, maxConnectionLifeTime=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@2450fe1, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@14f11e1d, socketFactory=javax.net.DefaultSocketFactory@736a091b, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=60000, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2020-01-26 15:59:11,179 [cluster-ClusterId{value='5e2d69f66300dd2b7bb150e0', description='null'}-localhost:27017] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:5, serverValue:12472}] to localhost:27017
2020-01-26 15:59:11,180 [cluster-ClusterId{value='5e2d69f66300dd2b7bb150e0', description='null'}-localhost:27017] INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 0, 10]}, minWireVersion=0, maxWireVersion=7, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=514046}
2020-01-26 15:59:13,043 [main] INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
2020-01-26 15:59:13,063 [main] INFO  o.s.j.e.a.AnnotationMBeanExporter - Bean with name 'configurationPropertiesRebinder' has been autodetected for JMX exposure
2020-01-26 15:59:13,063 [main] INFO  o.s.j.e.a.AnnotationMBeanExporter - Bean with name 'environmentManager' has been autodetected for JMX exposure
2020-01-26 15:59:13,064 [main] INFO  o.s.j.e.a.AnnotationMBeanExporter - Bean with name 'refreshScope' has been autodetected for JMX exposure
2020-01-26 15:59:13,066 [main] INFO  o.s.j.e.a.AnnotationMBeanExporter - Located managed bean 'environmentManager': registering with JMX server as MBean [org.springframework.cloud.context.environment:name=environmentManager,type=EnvironmentManager]
2020-01-26 15:59:13,088 [main] INFO  o.s.j.e.a.AnnotationMBeanExporter - Located managed bean 'refreshScope': registering with JMX server as MBean [org.springframework.cloud.context.scope.refresh:name=refreshScope,type=RefreshScope]
2020-01-26 15:59:13,109 [main] INFO  o.s.j.e.a.AnnotationMBeanExporter - Located managed bean 'configurationPropertiesRebinder': registering with JMX server as MBean [org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=472b826e,type=ConfigurationPropertiesRebinder]
2020-01-26 15:59:13,267 [main] INFO  com.capitalone.dashboard.Application - Started Application in 51.653 seconds (JVM running for 63.018)
2020-01-26 16:00:00,001 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Running Collector: Subversion
2020-01-26 16:00:00,039 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2020-01-26 16:00:00,039 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Starting...
2020-01-26 16:00:00,039 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2020-01-26 16:00:02,098 [taskScheduler-1] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
        at com.capitalone.dashboard.collector.DefaultSubversionClient.getCommits(DefaultSubversionClient.java:71) ~[subversion-collector.jar!/:3.1-SNAPSHOT]
        at com.capitalone.dashboard.collector.SubversionCollectorTask.collect(SubversionCollectorTask.java:147) ~[subversion-collector.jar!/:3.1-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-3.0.4.jar!/:3.1-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_222]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_222]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_222]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_222]
2020-01-26 16:01:07,654 [pool-3-thread-1] INFO  org.mongodb.driver.connection - Closed connection [connectionId{localValue:2, serverValue:12469}] to localhost:27017 because it is past its maximum allowed idle time.
2020-01-26 16:05:00,002 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Running Collector: Subversion
2020-01-26 16:05:00,199 [taskScheduler-1] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:6, serverValue:12481}] to localhost:27017
2020-01-26 16:05:00,204 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2020-01-26 16:05:00,204 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Starting...
2020-01-26 16:05:00,204 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2020-01-26 16:05:00,743 [taskScheduler-1] **ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null**
        at com.capitalone.dashboard.collector.DefaultSubversionClient.getCommits(DefaultSubversionClient.java:71) ~[subversion-collector.jar!/:3.1-SNAPSHOT]
        at com.capitalone.dashboard.collector.SubversionCollectorTask.collect(SubversionCollectorTask.java:147) ~[subversion-collector.jar!/:3.1-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-3.0.4.jar!/:3.1-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_222]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_222]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_222]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_222]
2020-01-26 16:06:07,654 [pool-3-thread-1] INFO  org.mongodb.driver.connection - Closed connection [connectionId{localValue:6, serverValue:12481}] to localhost:27017 because it is past its maximum allowed idle time.

**Comment by shubhamk0305** [comment]
properties file:


dbname=dashboarddb

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
dbreplicaset=[false if you are not using MongoDB replicaset]
dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=dbpassword

# Logging File location
logging.file=./logs/subversion.log

# Collector schedule (required)
subversion.cron=0 0/5 * * * *

# Shared subversion username and password
subversion.username=hygieia
subversion.password=hygieia
subversion.host=http://*.*.*.*

# Maximum number of previous days from current date, when fetching commits
subversion.commitThresholdDays=15


@rvema @Sbrenthughes   need help on this

**Comment by shubhamk0305** [comment]
i tried this with both collectors

earlier i was using 3.0.2 release and i have also tried with 
https://github.com/Hygieia/hygieia-scm-subversion-collector but getting same error on that

**Comment by shubhamk0305** [comment]
@rvema  @Sbrenthughes  please update on this???

**Comment by Shubhamk0503** [comment]
@mvineza can you help on this issue

**Comment by mvineza** [comment]
> @mvineza can you help on this issue

I haven't use this collector. But looking on your config seems there are things we need to cleanup first. Assuming these are not typos.

Provide the correct host here.
```
subversion.host=http://...
```

Remove these lines.
```
dbreplicaset=[false if you are not using MongoDB replicaset]
dbhostport=[host1:port1,host2:port2,host3:port3]
``` 

After the changes above, restart the collector and watch the logs.
